//list of duplicate names to remove from BCLR homepage
// last updated: 2/4/2022

var names_to_hide= [
    "Tom C. W. Lin",
    "Yaron G. Nili",
    "David Wilkins",
    "Harold Koh",
    "Jill W. Lens",
    "Shelly H. Welton",
    "John Ferraro",
    "D. Carolina Nunez",
    "Zachary D. Kaufman J.D., Ph.D.",
    "Troy Rule",
    "Rachel A. Minassian",
    "Scott Sullivan",
    "Susan Kuo",
    "Curtis R. Cooke",
    "John Shahar Dillbary",
    "Charles Korsmo",
    "Jonathan Lester",
    "Karrigan S. Bork",
    "Christopher Cotropia",
    "David Schwartz",
    "Rory T. Skowron",
    "Rachel Weiss",
    "Grant M. Hayden Professor",
    "Maxwell Fabiszewski",
    "Woodrow Hartzog 3735550",
    "Michael Kang",
    "Clark Asay",
    "Sandra Mayson",
    "Justin Pidot",
    "Meg Ziegler",
    "Hannah Wiseman",
    "Kyle Velte",
    "Camilla Hrdy",
    "Jillian Friedmann",
    "Alice Ristroph Brooklyn Law School / Harvard Law School",
    "Lauren Beausoleil",
    "Logan Hovie",
    "Emily Tate",
    "Julian A. Cook",
    "George Georgiev",
    "Marc McAllister",
    "amy semet",
    "Liza S. Vertinsky",
    "Cassady V. Brewer",
    "Amanda J. Peters",
    "Sebastian Lopez Escarcena",
    "Emmanuel Tetteh Laryea",
    "Rachel D. Thrasher",
    "Jonas Monast",
    "Emily Stolzenberg",
    "Jonas Anderson",
    "Robert Percival",
    "Dina Haynes",
    "Carlos Berdejo",
    "Bernard H. Chao",
    "Seth Endo",
    "Kelli A. Alces",
    "Chloe Booth",
    "Emily Tate",
    "Jonathan R. Nash",
    "Stephen Park",
    "Matthew C. Jennejohn",
    "Thomas F. Lampert",
    "Meghan Looney",
    "Brad Areheart",
    "Shalini Ray",
    "Gabriel Chin",
    "samir parikh",
    "Cary Shelby",
    "Chris Modlish",
    "Tom Murphy",
    "Isaac Buck",
    "Laura I Appleman",
    "Susan Kuo",
    "Dorit R. Reiss",
    "Paul Caron",
    "David Shakow",
    "Wendy Gerzog",
    "Rachel S. Arnow-Richman",
    "Jessica Roberts",
    "Erika Manderscheid",
    "Fredrick E. Vars",
    "David S. Olson",
    "Gregory Dolin",
    "John Coyle",
    "Sarah F. Russell",
    "Dawinder S. Sidhu",
    "Jordan Smith",
    "Sean J. Griffith",
    "David E. Landau",
    "Victoria Frances Nourse",
    "David Jaros",
    "M. Fan",
    "Rebecca Haw Allensworth",
    "Andrew Pollis",
    "Jordan Smith",
    "Steven L. Schwarcz",
    "Zachary Gubler",
    "Zoe D. Robinson",
    "Christopher Cifrino",
    "Lisa G. Sun",
    "Emily A. Jordan",
    "Stephanie Barclay",
    "Alexander Boni-Saenz",
    "Sarah Rajec",
    "Lea Johnston",
    "Rebecca Hamilton"
];